name: CI-Build-test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: src
      PROJECT_NAME_TESTS: src.tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: dotnet build ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj -c Release -o content

      - name: Run tests
        run: dotnet test ${{ env.PROJECT_NAME_TESTS }}/${{ env.PROJECT_NAME_TESTS }}.csproj
